apiVersion: v1
kind: Service
metadata:
  name: { include "prophet-materializer-questdb.fullname" . }
  labels:
    app.kubernetes.io/name: prophet-materializer-questdb
    app.kubernetes.io/part-of: prophet-platform
    socioprofit.com/atom: prophet-materializer-questdb
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: prophet-materializer-questdb
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
