apiVersion: v1
kind: ConfigMap
metadata:
  name: { include "prophet-materializer-clickhouse.fullname" . }-config
  labels:
    app.kubernetes.io/name: prophet-materializer-clickhouse
    app.kubernetes.io/part-of: prophet-platform
    socioprofit.com/atom: prophet-materializer-clickhouse
data:
  # Add non-secret config here
  LOG_LEVEL: "info"
