resource "google_project_service" "prototype_services" {
  for_each = var.enable_google_project_services ? var.google_project_services : []

  project            = var.google_project_id
  service            = each.value
  disable_on_destroy = false
}

resource "local_file" "apps_script_config" {
  count = var.generate_local_deployment_files ? 1 : 0

  filename = "${local.generated_dir}/config.generated.json"
  content  = jsonencode(local.apps_script_config)
}

resource "local_file" "clasp_config" {
  count = var.generate_local_deployment_files ? 1 : 0

  filename = "${local.generated_dir}/clasp.generated.json"
  content  = jsonencode(local.clasp_config)
}

resource "local_file" "mesh_summary" {
  count = var.generate_local_deployment_files ? 1 : 0

  filename = "${local.generated_dir}/mesh-summary.generated.json"
  content  = jsonencode(local.mesh_summary)
}

resource "local_file" "operator_next_steps" {
  count = var.generate_local_deployment_files ? 1 : 0

  filename = "${local.generated_dir}/operator-next-steps.md"
  content = <<-EOT
  # Operator Next Steps — Google Workspace Ops Mesh

  Generated by Terraform from `infra/google-workspace-ops-mesh`.

  ## 1. Validate repository scaffold

  ```bash
  python3 scripts/validate_google_workspace_ops_prototype.py
  ```

  ## 2. Review generated files

  - `config.generated.json`
  - `clasp.generated.json`
  - `mesh-summary.generated.json`

  ## 3. Copy generated config intentionally

  The generated clasp config should be reviewed before being copied to `.clasp.json`.

  ## 4. Keep dry-run enabled

  Current dry-run value: `${var.prototype_dry_run}`

  Do not disable dry-run until the handoff runbook gates pass.

  ## 5. Unsupported-by-default surfaces

  This Terraform mesh does not create calendars, Sheets, Apps Script projects, dashboard objects, Workspace groups, or scheduled triggers by default.
  EOT
}
