apiVersion: v1
kind: Service
metadata:
  name: { include "prophet-lake-writer.fullname" . }
  labels:
    app.kubernetes.io/name: prophet-lake-writer
    app.kubernetes.io/part-of: prophet-platform
    socioprofit.com/atom: prophet-lake-writer
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: prophet-lake-writer
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
