apiVersion: v1
kind: ConfigMap
metadata:
  name: { include "prophet-query-gateway.fullname" . }-config
  labels:
    app.kubernetes.io/name: prophet-query-gateway
    app.kubernetes.io/part-of: prophet-platform
    socioprofit.com/atom: prophet-query-gateway
data:
  # Add non-secret config here
  LOG_LEVEL: "info"
