apiVersion: v1
kind: Service
metadata:
  name: { include "prophet-query-gateway.fullname" . }
  labels:
    app.kubernetes.io/name: prophet-query-gateway
    app.kubernetes.io/part-of: prophet-platform
    socioprofit.com/atom: prophet-query-gateway
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: prophet-query-gateway
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
