cluster:
  name: ch01
  image: altinity/clickhouse-server:25.3.8.10041.altinitystable
  shardsCount: 1
  replicasCount: 2

storage:
  size: 200Gi
  storageClassName: standard

service:
  type: ClusterIP
  httpPort: 8123
  nativePort: 9000

resources:
  requests:
    cpu: "2"
    memory: "4Gi"
  limits:
    cpu: "8"
    memory: "16Gi"
