      image:
        repository: ghcr.io/socioprofit/prophet-materializer-clickhouse
        tag: "0.1.0"
        pullPolicy: IfNotPresent

      service:
        type: ClusterIP
  port: 8084

      env:
TARGET: "clickhouse"

      resources: {}
