image:
  repository: ghcr.io/socioprofit/socioprofit-worker
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8091

env:
  PROPHET_API_URL: "http://prophet-control-plane.prophet-system.svc.cluster.local:8080"

resources: {}
