apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arcticdb-gateway.fullname" . }}-config
data:
  ARCTIC_URI: {{ .Values.arcticdb.uri | quote }}
  ARCTIC_LIBRARY: {{ .Values.arcticdb.library | quote }}
