apiVersion: v1
kind: ConfigMap
metadata:
  name: { include "prophet-reasoner.fullname" . }-config
  labels:
    app.kubernetes.io/name: prophet-reasoner
    app.kubernetes.io/part-of: prophet-platform
    socioprofit.com/atom: prophet-reasoner
data:
  # Add non-secret config here
  LOG_LEVEL: "info"
