apiVersion: v1
kind: Service
metadata:
  name: { include "socioprofit-web.fullname" . }
  labels:
    app.kubernetes.io/name: socioprofit-web
    app.kubernetes.io/part-of: socioprofit
    prophet.ai/atom: socioprofit-web
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: socioprofit-web
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
