apiVersion: v1
kind: ConfigMap
metadata:
  name: { include "socioprofit-api.fullname" . }-config
  labels:
    app.kubernetes.io/name: socioprofit-api
    app.kubernetes.io/part-of: socioprofit
    prophet.ai/atom: socioprofit-api
data:
  LOG_LEVEL: "info"
